# Generated by Django 5.1.7 on 2025-03-09 03:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('Due Today', 'Due Today'), ('Upcoming', 'Upcoming'), ('Overdue', 'Overdue')], max_length=20)),
            ],
        ),
    ]
